version: '3.8'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"  # Opcional, apenas se você precisar acessar o MySQL fora do Docker

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: mysql
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/alurafood-pedidos?createDatabaseIfNotExist=true
    ports:
      - "8080:8080"
    depends_on:
      - mysql